export const repositoryURL = "https://github.com/p0s/arrive-within";
export const appStoreURL = "https://apps.apple.com/app/id6800192697";

export const siteContent = {
  en: {
    lang: "en",
    locale: "en-US",
    languageName: "English",
    switchLabel: "DE",
    nav: { home: "Home", practice: "Practice", privacy: "Privacy", openSource: "Open source", support: "Support", source: "Source on GitHub" },
    footer: {
      statement: "A private meditation garden for iPhone and iPad.",
      status: "Available on the App Store for iPhone and iPad.",
      copyright: "© 2026 Arrive Within contributors",
    },
    home: {
      metaTitle: "Arrive Within — Meditation that grows",
      metaDescription: "A private, offline-first meditation garden for iPhone and iPad. Practice your way and see one living world grow.",
      eyebrow: "Meditation that grows",
      title: "A quiet place to arrive.",
      intro: "A guided practice, a dependable timer, or an open-ended sit. Every qualifying practice becomes permanent, visible growth—without streak pressure, accounts, ads, or subscriptions.",
      primaryAction: "Download on the App Store",
      secondaryAction: "See how it grows",
      media: {
        kicker: "One garden, faithfully grown",
        title: "See practice become a living world.",
        body: "Follow the same garden from before the first practice through day 30.",
        label: "Garden-growth film showing the same garden from before the first practice through practice day 30.",
        fallback: "Open the garden-growth film",
        description: "Silent visual preview: the same garden begins with a small tree and becomes fuller across 30 qualifying practice days. The tree, path, water, and shelter stay in one continuous world. The film compresses progress; it does not show a single session or 30 consecutive calendar days.",
      },
      growth: {
        kicker: "Practice becomes place",
        title: "Show up. See it take root.",
        body: "Complete at least three active minutes to begin a tree. Later completed practices deepen the same tree and the world around it. Paused time does not count. Missed days remove nothing; progress comes only from completed practice.",
        facts: ["One persistent garden", "30 practice days", "Practice works offline"],
      },
      modes: {
        kicker: "Your practice, your shape",
        title: "Three quiet ways to begin.",
        body: "No mandatory tutorial or questionnaire. Choose the amount of structure that fits this moment.",
        items: [
          { name: "Guided", text: "Choose from 42 original English or German practices, with narration and transcripts packaged for offline playback." },
          { name: "Timer", text: "A dependable interval timer with calm bells, ambience, and saved preferences." },
          { name: "Stopwatch", text: "Sit without an endpoint. Finish when you are ready; the app never invents completion." },
        ],
      },
      starter: {
        kicker: "Your first few minutes",
        title: "Begin with a practice, not a streak.",
        intro: "Everything you need to meditate is free: guided practices, timer, stopwatch, reflections, and the complete growing garden. One optional, one-time purchase changes the garden’s material style; it never buys or speeds up progress.",
        steps: [
          { title: "Choose a quiet start", text: "Try Arrive Here, a three-minute guided practice, or set the timer for a length that fits. Sit, stand, or lie down where you can stay safely still." },
          { title: "Practice at your own pace", text: "English and German narration and transcripts are included for offline use after installation. You can pause, resume, or end when you need to." },
          { title: "Finish and let it grow", text: "A completed session with at least three active minutes adds permanent growth. The first qualifying session of a practice day advances your journey; more sessions that day add growth without skipping days. A shorter completed sit can stay in history. Miss a day and keep everything that has grown." },
        ],
        preview: {
          title: "Read an excerpt from Arrive Here",
          source: "Content/guided/G01/script.en.md",
          paragraphs: ["Choose a position that asks as little effort as possible. You can sit, stand, or lie down. If closing your eyes does not feel right, leave them open and let your gaze rest somewhere simple.", "Notice that the ground is already meeting you. Feel one or two places where your body is supported: feet on the floor, the seat beneath you, or the surface under your back."],
          note: "An excerpt from the original three-minute practice. The complete narration and transcript are in the app; this website does not run or save a session.",
        },
        privacy: "No Arrive Within account or cloud sync is needed. Practice and reflections stay on your device unless you deliberately export and share them.",
        action: "Start with Arrive Within",
      },
      journey: {
        kicker: "A rhythm without pressure",
        title: "See the days you returned.",
        body: "Journey keeps an honest calendar of completed practice and lasting milestones. Missing a day never removes what already grew.",
      },
      privacy: {
        kicker: "Private by design",
        title: "Your reflection is not a data source.",
        body: "Write or record an optional reflection. It stays on this device unless you deliberately export it. Arrive Within has no advertising, analytics, tracking, social feed, account, cloud sync, or user-data backend.",
        link: "Read the privacy policy",
      },
      open: {
        kicker: "Built in the open",
        title: "One canonical app, ready for public collaboration.",
        body: "The source, deterministic renderer, content contracts, tests, website, and release evidence live together in one public repository. No private overlay is required to build the real product.",
        link: "Explore the open-source project",
      },
    },
    support: {
      metaTitle: "Support — Arrive Within",
      metaDescription: "Support information and self-service answers for Arrive Within.",
      eyebrow: "Support",
      title: "Help without asking for your private data.",
      intro: "These answers describe the 1.0.2 release candidate. Version 1.0.1 remains the current App Store release.",
      feedbackLabel: "Open Settings, then choose Support",
      feedbackNote: "Neither the live 1.0.1 app nor the 1.0.2 candidate transmits in-app feedback. The Support link opens this page without attaching practice, journal, recording, transcript, screenshot, log, or device data.",
      faqs: [
        { q: "Does Arrive Within need an account?", a: "No. Practice, Garden progress, Journal, Journey, and reminders are stored locally and work without an account, backend, or cloud sync." },
        { q: "Does this version include guided narration?", a: "Yes. The live 1.0.1 app and 1.0.2 candidate include 42 original guided practices with approved English and German narration and bound transcripts, all packaged for offline playback. Timer and Stopwatch remain available." },
        { q: "How do I move or back up my data?", a: "Data & Storage creates a readable archive of saved data that you can deliberately share through Apple's system share sheet. Choose a complete archive in Files to restore it; restore replaces saved garden, practice, journal, voice, and favorite data, and removes unfinished text drafts. Language, timer preferences, reminders, and permissions stay on this device. Save a draft as an entry before exporting if you want it in the archive. The app keeps no cloud copy." },
        { q: "Can I delete everything?", a: "Yes. Local reset and delete-all are explicit. They remove local progress, journal content and audio, settings, and app-owned export archives." },
        { q: "Does the app send support or usage data?", a: "No. Version 1.0.1 links to this support page but has no analytics, advertising, tracking, backend, cloud sync, or in-app feedback transmission." },
        { q: "Is this medical treatment?", a: "No. Arrive Within is a secular meditation and reflection tool, not medical care, diagnosis, therapy, or crisis support." },
      ],
    },
    privacyPage: {
      metaTitle: "Privacy — Arrive Within",
      metaDescription: "The Arrive Within privacy promise: local device storage, no collection, and no tracking.",
      eyebrow: "Privacy",
      title: "Your practice stays yours.",
      intro: "Effective 25 September 2026. This policy covers the 1.0.2 release candidate; 1.0.1 remains the current App Store release until a new version is approved and published.",
      sections: [
        { title: "What the app stores", paragraphs: ["Practice sessions, Garden progress, preferences, favorites, reminder schedules, saved journal entries, and unfinished journal text drafts in the 1.0.2 candidate are stored on your device.", "Journal voice recordings are app data. On-device transcription is optional; Arrive Within does not send recordings to a custom AI service or browser speech service."] },
        { title: "Where it stays", paragraphs: ["The 1.0.2 candidate stores app data on this device. It has no account, backend, or cloud sync. Version 1.0.1 remains the current published release.", "You can choose a complete archive in Files and restore it locally. The app reads that selected file without uploading it. Data leaves the app only when you deliberately create an export and share it through Apple's system share sheet. Unfinished drafts are not included until saved as entries. Copies you share are then controlled by the destination you choose."] },
        { title: "What we do not do", paragraphs: ["No third-party analytics, advertising SDK, tracking, ATT prompt, social graph, newsletter, data broker, or cross-app profiling is part of 1.0.1.", "The renderer has no network authority. Your journal is not analyzed for recommendations, scoring, or advertising."] },
        { title: "Support", paragraphs: ["Settings links to the public Support and Privacy pages. Neither version 1.0.1 nor the 1.0.2 candidate prepares or transmits an in-app feedback report.", "No practice or journal content, recording, transcript, screenshot, clipboard content, renderer state, log, credential, analytics, or identifier is attached to those links."] },
        { title: "Permissions", paragraphs: ["Microphone access is requested only when you choose to record a voice reflection. Speech-recognition access is requested only when you choose on-device transcription. Notification permission is requested only when you create reminders.", "Permission denial keeps the rest of the app usable and preserves any text you already entered."] },
        { title: "Export, restore, reset, and deletion", paragraphs: ["You can create a readable export, restore a complete archive selected from Files, and explicitly reset or delete local data. Restore replaces saved Garden, practice, journal, voice, and favorite data, and removes unfinished drafts. Language, timer preferences, reminders, and permissions stay on this device. App-owned export archives are protected, excluded from backup, limited to one, removed after sharing closes, and purged during reset or delete-all.", "Before sharing an export, review it for content you consider private. The app cannot remove copies that you deliberately share elsewhere."] },
        { title: "Questions and policy updates", paragraphs: ["The canonical support route is /support.", "This policy is kept aligned with the exact app binary, PrivacyInfo.xcprivacy, App Privacy answers, permission strings, and public support channel."] },
      ],
      analyticsChoice: {
        title: "Website request counts",
        paragraphs: ["This public website counts eligible public HTML document requests at its Cloudflare edge, including cached documents, only after the static asset response is HTTP 200 with HTML content. Eligibility is limited to known public document routes. It uses no browser tracker, advertising identifier, cookie banner, or cross-site identity.", "The server sends the public path, referring origin, country from Cloudflare request metadata, and transient IP/User-Agent data to estimate aggregate sessions. The ingestion service discards the raw IP and User-Agent after processing; retained website data follows a 13-month policy, with encrypted operational backup copies expiring within 30 days after live removal. This is scoped to this website and separate from the Arrive Within app, which remains local-first and has no analytics.", "Use either control below at any time. The preference cookie is host-only, Secure, HttpOnly, and used only to honor this choice. DNT and Global Privacy Control are always honored."],
        optOutLabel: "Exclude this browser",
        optInLabel: "Include this browser again",
      },
    },
    openSourcePage: {
      metaTitle: "Open source — Arrive Within",
      metaDescription: "Explore and contribute to the canonical public source for the Arrive Within iPhone and iPad app.",
      eyebrow: "Open-source commitment",
      title: "The public repository is the real product.",
      intro: "Arrive Within is developed in one canonical public repository whose tracked history is safe to inspect from the first commit.",
      principles: [
        { title: "No demo fork", text: "The native app, renderer, content contracts, website, tests, and release evidence live together in this repository. There is no private product behind a public shell." },
        { title: "Reproducible evidence", text: "Deterministic fixtures and public-safe ledgers separate local tests, simulator proof, physical devices, CloudKit, TestFlight, App Store, and deployment readback." },
        { title: "Rights before assets", text: "No copied reference art, uncertain voice material, proprietary behavior, or unreviewed media enters the public history." },
        { title: "Privacy as architecture", text: "The app is local-first, has no tracking or custom user-data backend, and keeps the renderer outside product authority." },
      ],
      repoLabel: "View source on GitHub",
      repoNote: "Browse the app, renderer, tests, contributor guides, and public evidence, or propose a focused improvement.",
    },
  },
  de: {
    lang: "de",
    locale: "de-DE",
    languageName: "Deutsch",
    switchLabel: "EN",
    nav: { home: "Start", practice: "Meditieren", privacy: "Datenschutz", openSource: "Open Source", support: "Hilfe", source: "Quellcode auf GitHub" },
    footer: {
      statement: "Ein privater Meditationsgarten für iPhone und iPad.",
      status: "Im App Store für iPhone und iPad verfügbar.",
      copyright: "© 2026 Mitwirkende von Arrive Within",
    },
    home: {
      metaTitle: "Arrive Within — Meditation, die wächst",
      metaDescription: "Ein privater, offline nutzbarer Meditationsgarten für iPhone und iPad. Meditiere auf deine Art und lass eine lebendige Welt wachsen.",
      eyebrow: "Meditation, die wächst",
      title: "Ein stiller Ort zum Ankommen.",
      intro: "Eine geführte Meditation, ein verlässlicher Timer oder eine offene Stoppuhr. Jede qualifizierende Praxis wird zu dauerhaftem, sichtbarem Wachstum – ohne Streak-Druck, Konto, Werbung oder Abo.",
      primaryAction: "Im App Store laden",
      secondaryAction: "Wachstum ansehen",
      media: {
        kicker: "Ein Garten, verlässlich gewachsen",
        title: "Sieh, wie Praxis zu einer lebendigen Welt wird.",
        body: "Begleite denselben Garten von vor der ersten Meditation bis zum 30. Praxistag.",
        label: "Gartenfilm, der denselben Garten von vor der ersten Meditation bis zum 30. Praxistag zeigt.",
        fallback: "Gartenfilm öffnen",
        description: "Stumme Vorschau: Derselbe Garten beginnt mit einem kleinen Baum und wird über 30 qualifizierende Praxistage voller. Baum, Weg, Wasser und Unterstand bleiben Teil derselben Welt. Der Film fasst den Fortschritt zusammen; er zeigt weder eine einzelne Sitzung noch 30 aufeinanderfolgende Kalendertage.",
      },
      growth: {
        kicker: "Praxis wird zu einem Ort",
        title: "Komm wieder. Lass ihn Wurzeln schlagen.",
        body: "Eine abgeschlossene Praxis mit mindestens drei aktiven Minuten lässt einen Baum entstehen. Weitere abgeschlossene Meditationen lassen denselben Baum und seine Umgebung wachsen. Pausenzeit zählt nicht mit. Ausgelassene Tage nehmen dir nichts; nur abgeschlossene Praxis bringt Fortschritt.",
        facts: ["Ein bleibender Garten", "30 Praxistage", "Praxis auch offline"],
      },
      modes: {
        kicker: "Deine Praxis, deine Form",
        title: "Drei ruhige Wege zu beginnen.",
        body: "Kein verpflichtendes Tutorial und kein Fragebogen. Wähle so viel Struktur, wie dieser Moment braucht.",
        items: [
          { name: "Geführt", text: "Wähle aus 42 originalen englischen oder deutschen Meditationen mit vollständig offline verfügbaren Audios und Transkripten." },
          { name: "Timer", text: "Ein verlässlicher Intervalltimer mit ruhigen Klängen, Atmosphäre und gespeicherten Einstellungen." },
          { name: "Stoppuhr", text: "Sitze ohne Endzeit. Du beendest die Praxis; die App erfindet keinen Abschluss." },
        ],
      },
      starter: {
        kicker: "Deine ersten Minuten",
        title: "Beginne mit einer Meditation, ohne Streak-Druck.",
        intro: "Alles für deine Meditation bleibt kostenlos: geführte Übungen, Timer, Stoppuhr, Reflexionen und der vollständige wachsende Garten. Ein optionaler Einmalkauf verändert den Materialstil des Gartens; Fortschritt lässt sich weder kaufen noch beschleunigen.",
        steps: [
          { title: "Wähle einen ruhigen Einstieg", text: "Probiere Hier ankommen, eine dreiminütige geführte Übung, oder stelle den Timer passend zu deinem Moment ein. Sitze, stehe oder liege an einem Ort, an dem du sicher in Ruhe bleiben kannst." },
          { title: "Übe in deinem Tempo", text: "Englische und deutsche Audios und Transkripte sind nach der Installation offline verfügbar. Du kannst pausieren, fortsetzen oder aufhören, wenn du es brauchst." },
          { title: "Schließe ab und lass es wachsen", text: "Eine abgeschlossene Sitzung mit mindestens drei aktiven Minuten bringt dauerhaftes Wachstum. Die erste qualifizierende Sitzung eines Praxistags bringt deinen Weg einen Tag weiter; zusätzliche Sitzungen lassen den Garten wachsen, ohne Tage zu überspringen. Eine kürzere abgeschlossene Übung kann im Verlauf bleiben. Wenn du einen Tag auslässt, bleibt alles Gewachsene erhalten." },
        ],
        preview: {
          title: "Lies einen Auszug aus Hier ankommen",
          source: "Content/guided/G01/script.de.md",
          paragraphs: ["Wähle eine Haltung, die möglichst wenig Anstrengung verlangt. Du kannst sitzen, stehen oder liegen. Wenn es sich nicht gut anfühlt, die Augen zu schließen, lass sie offen und den Blick an einer ruhigen Stelle verweilen.", "Bemerke, dass der Boden dir bereits entgegenkommt. Spüre ein oder zwei Stellen, an denen dein Körper getragen wird: die Füße auf dem Boden, die Sitzfläche unter dir oder die Unterlage unter deinem Rücken."],
          note: "Ein Auszug aus der originalen dreiminütigen Übung. Das vollständige Audio und Transkript findest du in der App; diese Website führt keine Sitzung aus und speichert keine Praxis.",
        },
        privacy: "Du brauchst weder ein Arrive-Within-Konto noch Cloud-Synchronisierung. Praxis und Reflexionen bleiben auf deinem Gerät, sofern du sie nicht bewusst exportierst und teilst.",
        action: "Mit Arrive Within beginnen",
      },
      journey: {
        kicker: "Ein Rhythmus ohne Druck",
        title: "Sieh die Tage, an denen du wiederkamst.",
        body: "Dein Weg bewahrt einen ehrlichen Kalender vollendeter Praxis und bleibender Meilensteine. Ein Pausentag nimmt dir nichts, was bereits gewachsen ist.",
      },
      privacy: {
        kicker: "Privat von Grund auf",
        title: "Deine Reflexion ist keine Datenquelle.",
        body: "Schreibe oder sprich optional einen Gedanken ein. Er bleibt auf diesem Gerät, sofern du ihn nicht ausdrücklich exportierst. Arrive Within hat keine Werbung, Analyse, Nachverfolgung, Social-Funktion, Konto, Cloud-Synchronisierung oder Nutzerdaten-Server.",
        link: "Lies die Datenschutzerklärung",
      },
      open: {
        kicker: "Offen entwickelt",
        title: "Eine echte App, vorbereitet für öffentliche Zusammenarbeit.",
        body: "Quellcode, deterministischer Renderer, Inhaltsverträge, Tests, Website und Freigabenachweise leben gemeinsam in einem öffentlichen Repository. Für das echte Produkt ist keine private Zusatzschicht nötig.",
        link: "Entdecke das Open-Source-Projekt",
      },
    },
    support: {
      metaTitle: "Hilfe — Arrive Within",
      metaDescription: "Hilfe und Antworten zur Selbsthilfe für Arrive Within.",
      eyebrow: "Hilfe",
      title: "Unterstützung, ohne nach deinen privaten Daten zu fragen.",
      intro: "Diese Antworten beschreiben die Release-Kandidatin 1.0.2. Version 1.0.1 ist weiterhin die aktuelle App-Store-Version.",
      feedbackLabel: "Öffne Einstellungen und wähle Hilfe",
      feedbackNote: "Weder die veröffentlichte Version 1.0.1 noch die Kandidatin 1.0.2 überträgt Rückmeldungen aus der App. Der Hilfe-Link öffnet diese Seite, ohne Praxis-, Journal-, Aufnahme-, Transkript-, Bildschirmfoto-, Protokoll- oder Gerätedaten anzuhängen.",
      faqs: [
        { q: "Braucht Arrive Within ein Konto?", a: "Nein. Praxis, Garten, Journal, Weg und Erinnerungen werden lokal gespeichert und funktionieren ohne Konto, Backend oder Cloud-Synchronisierung." },
        { q: "Enthält diese Version geführte Meditationen?", a: "Ja. Die veröffentlichte Version 1.0.1 und die Kandidatin 1.0.2 enthalten 42 originale geführte Meditationen mit freigegebenen englischen und deutschen Audios sowie gebundenen Transkripten, vollständig für die Offline-Wiedergabe verpackt. Timer und Stoppuhr bleiben verfügbar." },
        { q: "Wie sichere oder übertrage ich meine Daten?", a: "Daten & Speicher erstellt ein lesbares Archiv gespeicherter Daten, das du ausdrücklich über Apples Teilen-Funktion weitergeben kannst. Wähle in Dateien ein vollständiges Archiv zur Wiederherstellung aus; dabei werden Garten, Praxis, Journal, Sprachdateien und Favoriten ersetzt und ungespeicherte Textentwürfe entfernt. Sprache, Timer-Einstellungen, Erinnerungen und Berechtigungen bleiben auf diesem Gerät. Speichere einen Entwurf als Eintrag, wenn du ihn exportieren möchtest. Die App bewahrt keine Cloud-Kopie auf." },
        { q: "Kann ich alles löschen?", a: "Ja. Lokales Zurücksetzen und vollständiges Löschen sind ausdrücklich bestätigt. Sie entfernen Fortschritt, Journalinhalt und -audio, ungespeicherte Textentwürfe, Einstellungen und app-eigene Exportarchive." },
        { q: "Sendet die App Hilfe- oder Nutzungsdaten?", a: "Nein. Version 1.0.1 verlinkt auf diese Hilfeseite, enthält aber weder Analyse, Werbung, Nachverfolgung, Backend, Cloud-Synchronisierung noch eine Rückmeldungsübertragung aus der App." },
        { q: "Ist die App eine medizinische Behandlung?", a: "Nein. Arrive Within ist ein weltliches Werkzeug für Meditation und Reflexion, keine medizinische Versorgung, Diagnose, Therapie oder Krisenhilfe." },
      ],
    },
    privacyPage: {
      metaTitle: "Datenschutz — Arrive Within",
      metaDescription: "Das Datenschutzversprechen von Arrive Within: lokale Gerätespeicherung, keine Datenerfassung und keine Nachverfolgung.",
      eyebrow: "Datenschutz",
      title: "Deine Praxis bleibt deine.",
      intro: "Gültig ab 25. September 2026. Diese Richtlinie gilt für die Release-Kandidatin Arrive Within 1.0.2; bis zu ihrer Veröffentlichung bleibt Version 1.0.1 im App Store aktuell.",
      sections: [
        { title: "Was die App speichert", paragraphs: ["Praxissitzungen, Gartenfortschritt, Einstellungen, Favoriten, Erinnerungspläne, gespeicherte Journaleinträge und nicht abgeschlossene Journaltextentwürfe der Kandidatin 1.0.2 bleiben auf deinem Gerät.", "Sprachaufnahmen sind App-Daten. Die Transkription auf dem Gerät ist optional; Arrive Within sendet Aufnahmen nicht an einen eigenen KI-Dienst oder einen Browser-Sprachdienst."] },
        { title: "Wo die Daten bleiben", paragraphs: ["Die Kandidatin 1.0.2 speichert App-Daten auf diesem Gerät. Es gibt weder Konto, Backend noch Cloud-Synchronisierung. Version 1.0.1 bleibt die veröffentlichte Version.", "Du kannst in Dateien ein vollständiges Archiv auswählen und lokal wiederherstellen. Die App liest diese Datei, ohne sie hochzuladen. Daten verlassen die App nur, wenn du ausdrücklich ein Archiv erstellst und es über Apples Teilen-Funktion weitergibst. Ungespeicherte Entwürfe werden erst nach dem Speichern als Journaleintrag eingeschlossen. Geteilte Kopien werden anschließend vom gewählten Ziel verwaltet."] },
        { title: "Was wir nicht tun", paragraphs: ["Keine Drittanbieter-Analyse, Werbe-SDKs, Nachverfolgung, ATT-Abfrage, Social Graph, Newsletter, Datenhändler oder App-übergreifende Profile gehören zu 1.0.1.", "Der Renderer hat keine Netzwerkbefugnis. Dein Journal wird nicht für Empfehlungen, Bewertungen oder Werbung analysiert."] },
        { title: "Hilfe", paragraphs: ["Einstellungen verlinkt auf die öffentlichen Hilfe- und Datenschutzseiten. Weder Version 1.0.1 noch die Kandidatin 1.0.2 erstellt oder überträgt einen Rückmeldungsbericht in der App.", "Praxis- oder Journalinhalte, Aufnahmen, Transkripte, Bildschirmfotos, Zwischenablage, Darstellungszustand, Protokolle, Zugangsdaten, Analysen und Kennungen werden diesen Links nicht angehängt."] },
        { title: "Berechtigungen", paragraphs: ["Mikrofonzugriff wird nur angefragt, wenn du eine Sprachreflexion aufnimmst. Spracherkennung nur bei gewählter Transkription auf dem Gerät. Mitteilungen nur beim Erstellen von Erinnerungen.", "Eine Ablehnung lässt den Rest der App nutzbar und bewahrt bereits eingegebenen Text."] },
        { title: "Export, Wiederherstellung, Zurücksetzen und Löschen", paragraphs: ["Du kannst ein lesbares Archiv erstellen, ein vollständiges ausgewähltes Archiv lokal wiederherstellen und lokale Daten ausdrücklich zurücksetzen oder löschen. Eine Wiederherstellung ersetzt Garten, Praxisverlauf, Journal, Sprachdaten und Favoriten; ungespeicherte Entwürfe werden entfernt. Sprache, Timer-Einstellungen, Erinnerungen und Berechtigungen bleiben auf diesem Gerät. App-eigene Exportarchive sind geschützt, von Backups ausgeschlossen, auf eines begrenzt, werden nach dem Schließen der Teilen-Funktion entfernt und beim Zurücksetzen oder vollständigen Löschen bereinigt.", "Prüfe ein Archiv vor dem Teilen auf private Inhalte. Die App kann Kopien, die du ausdrücklich anderswo teilst, nicht entfernen."] },
        { title: "Fragen und Aktualisierungen", paragraphs: ["Die kanonische Hilfeseite ist /de/support.", "Diese Richtlinie wird mit dem exakten App-Binary, PrivacyInfo.xcprivacy, den App-Privacy-Angaben, Berechtigungstexten und dem öffentlichen Hilfeweg im Einklang gehalten."] },
      ],
      analyticsChoice: {
        title: "Website-Anfragezählung",
        paragraphs: ["Diese öffentliche Website zählt berechtigte öffentliche HTML-Dokumentanfragen am Cloudflare-Edge, auch wenn das Dokument aus dem Cache kommt, und zwar erst, wenn die statische Antwort HTTP 200 mit HTML-Inhalt ist. Die Berechtigung ist auf bekannte öffentliche Dokumentrouten begrenzt. Es gibt keinen Browser-Tracker, keine Werbekennung, kein Cookie-Banner und keine websiteübergreifende Identität.", "Der Server sendet den öffentlichen Pfad, die Herkunft der verweisenden Seite, das Land aus Cloudflare-Anfragemetadaten sowie vorübergehend IP- und User-Agent-Daten, um Sitzungen aggregiert zu schätzen. Der Empfangsdienst verwirft die rohe IP und den User-Agent nach der Verarbeitung; Website-Daten werden nach einer Richtlinie von 13 Monaten aufbewahrt, verschlüsselte betriebliche Sicherungskopien laufen innerhalb von 30 Tagen nach der Entfernung aus dem Live-System ab. Die Verarbeitung ist auf diese Website begrenzt und von der Arrive Within App getrennt, die lokal ausgerichtet bleibt und keine Analysen enthält.", "Du kannst unten jederzeit eine Auswahl treffen. Das Präferenz-Cookie ist nur für diese Domain gültig, sicher, HttpOnly und dient ausschließlich der Umsetzung deiner Wahl. DNT und Global Privacy Control werden immer beachtet."],
        optOutLabel: "Diesen Browser ausschließen",
        optInLabel: "Diesen Browser wieder einschließen",
      },
    },
    openSourcePage: {
      metaTitle: "Open Source — Arrive Within",
      metaDescription: "Entdecke den kanonischen öffentlichen Quellcode der Arrive Within App für iPhone und iPad und wirke daran mit.",
      eyebrow: "Open-Source-Versprechen",
      title: "Das öffentliche Repository ist das echte Produkt.",
      intro: "Arrive Within wird in einem kanonischen öffentlichen Repository entwickelt, dessen gesamte nachverfolgte Historie ab dem ersten Commit sicher einsehbar ist.",
      principles: [
        { title: "Kein Demo-Fork", text: "Native App, Renderer, Inhaltsverträge, Website, Tests und Freigabenachweise gehören zu diesem Repository. Hinter einer öffentlichen Hülle liegt kein privates Produkt." },
        { title: "Reproduzierbare Nachweise", text: "Deterministische Fixtures und öffentlich sichere Ledgers trennen lokale Tests, Simulator, echte Geräte, CloudKit, TestFlight, App Store und Deployment-Readback." },
        { title: "Rechte vor Assets", text: "Kopierte Referenzkunst, unklare Stimmen, proprietäres Verhalten und ungeprüfte Medien gelangen nicht in die öffentliche Historie." },
        { title: "Datenschutz als Architektur", text: "Die App ist lokal ausgerichtet, hat kein Tracking und keinen eigenen Nutzerdaten-Server; der Renderer besitzt keine Produktwahrheit." },
      ],
      repoLabel: "Quellcode auf GitHub ansehen",
      repoNote: "Durchsuche App, Renderer, Tests, Leitfäden und öffentliche Nachweise oder schlage eine gezielte Verbesserung vor.",
    },
  },
};
