export const repositoryURL = "https://github.com/p0s/arrive-within";

export const siteContent = {
  en: {
    lang: "en",
    locale: "en-US",
    languageName: "English",
    switchLabel: "DE",
    nav: { home: "Home", practice: "Practice", privacy: "Privacy", openSource: "Open source", support: "Support", source: "Source on GitHub" },
    footer: {
      statement: "A private meditation garden for iPhone and iPad.",
      status: "The source is public. App Store availability has not been announced.",
      copyright: "© 2026 Arrive Within contributors",
    },
    home: {
      metaTitle: "Arrive Within — Meditation that grows",
      metaDescription: "A private, offline-first meditation garden for iPhone and iPad. Practice your way and see one living world grow.",
      eyebrow: "Meditation that grows",
      title: "A quiet place to arrive.",
      intro: "A dependable timer or an open-ended sit. Every qualifying practice becomes permanent, visible growth—without streak pressure, accounts, ads, or subscriptions.",
      primaryAction: "See how it grows",
      secondaryAction: "Read the privacy promise",
      visualNote: "Actual Arrive Within UI · deterministic safe sample data",
      media: {
        kicker: "One garden, faithfully grown",
        title: "See practice become a living world.",
        body: "Six deterministic states from the real Arrive Within renderer show the same garden from before the first practice through practice day 30. The silent film uses safe sample state, contains no generated interpolation, and makes no physical-device performance claim.",
        label: "Silent garden-growth film showing six deterministic stages from before the first practice to practice day 30.",
        caption: "Real renderer · deterministic safe sample state · 9.73 seconds · no audio",
        fallback: "Open the garden-growth film",
      },
      growth: {
        kicker: "Practice becomes place",
        title: "Show up. See it take root.",
        body: "Your first three minutes begin a tree. Later practices deepen the same tree and the world around it. Missed days remove nothing; progress comes only from completed practice.",
        facts: ["One persistent garden", "30 practice-day milestones", "A truthful native fallback"],
      },
      modes: {
        kicker: "Your practice, your shape",
        title: "Two quiet ways to begin.",
        body: "No mandatory tutorial or questionnaire. Choose the amount of structure that fits this moment.",
        items: [
          { name: "Timer", text: "A dependable interval timer with calm bells, ambience, and saved preferences." },
          { name: "Stopwatch", text: "Sit without an endpoint. Finish when you are ready; the app never invents completion." },
        ],
      },
      journey: {
        kicker: "A rhythm without pressure",
        title: "See the days you returned.",
        body: "Journey keeps an honest calendar of completed practice and lasting milestones. Missing a day never removes what already grew.",
      },
      privacy: {
        kicker: "Private by design",
        title: "Your reflection is not a data source.",
        body: "Write or record an optional reflection. It stays on this device unless you deliberately export it. Arrive Within has no advertising, analytics, tracking, social feed, account, cloud sync, or user-data backend.",
        link: "Read the privacy policy",
      },
      open: {
        kicker: "Built in the open",
        title: "One canonical app, ready for public collaboration.",
        body: "The source, deterministic renderer, content contracts, tests, website, and release evidence live together in one public repository. No private overlay is required to build the real product.",
        link: "Explore the open-source project",
      },
    },
    support: {
      metaTitle: "Support — Arrive Within",
      metaDescription: "Support information and self-service answers for Arrive Within.",
      eyebrow: "Support",
      title: "Help without asking for your private data.",
      intro: "These answers describe version 1.0. The app links here from Settings and does not send a support report or product data.",
      feedbackLabel: "Open Settings, then choose Support",
      feedbackNote: "Version 1.0 has no in-app feedback transmission. The Support link opens this public page without attaching practice, journal, recording, transcript, screenshot, log, or device data.",
      faqs: [
        { q: "Does Arrive Within need an account?", a: "No. Practice, Garden progress, Journal, Journey, and reminders are stored locally and work without an account, backend, or cloud sync." },
        { q: "Does this version include guided narration?", a: "No. This version offers the complete Timer and Stopwatch modes. Original bilingual offline narration is planned for a later update after rights, mastering, and fluent human review pass." },
        { q: "How do I move or back up my data?", a: "Data & Storage creates a readable archive that you can deliberately share through Apple's system share sheet. The app keeps no cloud copy." },
        { q: "Can I delete everything?", a: "Yes. Local reset and delete-all are explicit. They remove local progress, journal content and audio, settings, and app-owned export archives." },
        { q: "Does the app send support or usage data?", a: "No. Version 1.0 links to this support page but has no analytics, advertising, tracking, backend, cloud sync, or in-app feedback transmission." },
        { q: "Is this medical treatment?", a: "No. Arrive Within is a secular meditation and reflection tool, not medical care, diagnosis, therapy, or crisis support." },
      ],
    },
    privacyPage: {
      metaTitle: "Privacy — Arrive Within",
      metaDescription: "The Arrive Within privacy promise: local device storage, no collection, and no tracking.",
      eyebrow: "Privacy",
      title: "Your practice stays yours.",
      intro: "Effective 12 August 2026. This policy describes Arrive Within 1.0 and is kept aligned with the app and its public support channel.",
      sections: [
        { title: "What the app stores", paragraphs: ["Practice sessions, Garden progress, preferences, favorites, reminder schedules, and optional journal text or voice reflections are stored on your device.", "Journal voice recordings are app data. On-device transcription is optional; Arrive Within does not send recordings to a custom AI service or browser speech service."] },
        { title: "Where it stays", paragraphs: ["Version 1.0 stores app data on this device. It has no account, backend, or cloud sync.", "Data leaves the app only when you deliberately create an export and share it through Apple's system share sheet. Copies you share are then controlled by the destination you choose."] },
        { title: "What we do not do", paragraphs: ["No third-party analytics, advertising SDK, tracking, ATT prompt, social graph, newsletter, data broker, or cross-app profiling is part of 1.0.", "The renderer has no network authority. Your journal is not analyzed for recommendations, scoring, or advertising."] },
        { title: "Support", paragraphs: ["Settings links to the public Support and Privacy pages. Version 1.0 does not prepare or transmit an in-app feedback report.", "No practice or journal content, recording, transcript, screenshot, clipboard content, renderer state, log, credential, analytics, or identifier is attached to those links."] },
        { title: "Permissions", paragraphs: ["Microphone access is requested only when you choose to record a voice reflection. Speech-recognition access is requested only when you choose on-device transcription. Notification permission is requested only when you create reminders.", "Permission denial keeps the rest of the app usable and preserves any text you already entered."] },
        { title: "Export, reset, and deletion", paragraphs: ["You can create a readable export and explicitly reset or delete local data. App-owned export archives are protected, excluded from backup, limited to one, removed after sharing closes, and purged during reset or delete-all.", "Before sharing an export, review it for content you consider private. The app cannot remove copies that you deliberately share elsewhere."] },
        { title: "Questions and policy updates", paragraphs: ["The canonical support route is /support.", "This policy is kept aligned with the exact app binary, PrivacyInfo.xcprivacy, App Privacy answers, permission strings, and public support channel."] },
      ],
    },
    openSourcePage: {
      metaTitle: "Open source — Arrive Within",
      metaDescription: "Explore and contribute to the canonical public source for the Arrive Within iPhone and iPad app.",
      eyebrow: "Open-source commitment",
      title: "The public repository is the real product.",
      intro: "Arrive Within is developed in one canonical public repository whose tracked history is safe to inspect from the first commit.",
      principles: [
        { title: "No demo fork", text: "The native app, renderer, content contracts, website, tests, and release evidence live together. There is no private product implementation behind a public shell." },
        { title: "Reproducible evidence", text: "Deterministic fixtures and public-safe ledgers separate local tests, simulator proof, physical devices, CloudKit, TestFlight, App Store, and deployment readback." },
        { title: "Rights before assets", text: "No copied reference art, uncertain voice material, proprietary behavior, or unreviewed media enters the public history." },
        { title: "Privacy as architecture", text: "The app is local-first, has no tracking or custom user-data backend, and keeps the renderer outside product authority." },
      ],
      repoLabel: "View source on GitHub",
      repoNote: "Browse the app, renderer, tests, contributor guides, and public evidence, or propose a focused improvement.",
    },
  },
  de: {
    lang: "de",
    locale: "de-DE",
    languageName: "Deutsch",
    switchLabel: "EN",
    nav: { home: "Start", practice: "Meditieren", privacy: "Datenschutz", openSource: "Open Source", support: "Hilfe", source: "Quellcode auf GitHub" },
    footer: {
      statement: "Ein privater Meditationsgarten für iPhone und iPad.",
      status: "Der Quellcode ist öffentlich. Eine Verfügbarkeit im App Store wurde noch nicht angekündigt.",
      copyright: "© 2026 Mitwirkende von Arrive Within",
    },
    home: {
      metaTitle: "Arrive Within — Meditation, die wächst",
      metaDescription: "Ein privater, offline nutzbarer Meditationsgarten für iPhone und iPad. Meditiere auf deine Art und lass eine lebendige Welt wachsen.",
      eyebrow: "Meditation, die wächst",
      title: "Ein stiller Ort zum Ankommen.",
      intro: "Ein verlässlicher Timer oder eine offene Stoppuhr. Jede qualifizierende Praxis wird zu dauerhaftem, sichtbarem Wachstum – ohne Streak-Druck, Konto, Werbung oder Abo.",
      primaryAction: "Sieh, wie der Garten wächst",
      secondaryAction: "Lies unser Datenschutzversprechen",
      visualNote: "Echte Arrive Within Oberfläche · sichere deterministische Beispieldaten",
      media: {
        kicker: "Ein Garten, verlässlich gewachsen",
        title: "Sieh, wie Praxis zu einer lebendigen Welt wird.",
        body: "Sechs deterministische Zustände aus dem echten Arrive Within Renderer zeigen denselben Garten vor der ersten Meditation bis zum 30. Praxistag. Der stumme Film nutzt sichere Beispieldaten, enthält keine generierte Zwischenanimation und macht keine Aussage zur Leistung auf echten Geräten.",
        label: "Stummer Gartenfilm mit sechs deterministischen Stufen vor der ersten Meditation bis zum 30. Praxistag.",
        caption: "Echter Renderer · sichere deterministische Beispieldaten · 9,73 Sekunden · ohne Ton",
        fallback: "Gartenfilm öffnen",
      },
      growth: {
        kicker: "Praxis wird zu einem Ort",
        title: "Komm wieder. Lass ihn Wurzeln schlagen.",
        body: "Die ersten drei Minuten beginnen einen Baum. Weitere Meditationen vertiefen denselben Baum und seine Umgebung. Pausentage nehmen dir nichts; Fortschritt entsteht nur durch vollendete Praxis.",
        facts: ["Ein bleibender Garten", "30 Meilensteine nach Praxistagen", "Eine ehrliche native Ersatzansicht"],
      },
      modes: {
        kicker: "Deine Praxis, deine Form",
        title: "Zwei ruhige Wege zu beginnen.",
        body: "Kein verpflichtendes Tutorial und kein Fragebogen. Wähle so viel Struktur, wie dieser Moment braucht.",
        items: [
          { name: "Timer", text: "Ein verlässlicher Intervalltimer mit ruhigen Klängen, Atmosphäre und gespeicherten Einstellungen." },
          { name: "Stoppuhr", text: "Sitze ohne Endzeit. Du beendest die Praxis; die App erfindet keinen Abschluss." },
        ],
      },
      journey: {
        kicker: "Ein Rhythmus ohne Druck",
        title: "Sieh die Tage, an denen du wiederkamst.",
        body: "Dein Weg bewahrt einen ehrlichen Kalender vollendeter Praxis und bleibender Meilensteine. Ein Pausentag nimmt dir nichts, was bereits gewachsen ist.",
      },
      privacy: {
        kicker: "Privat von Grund auf",
        title: "Deine Reflexion ist keine Datenquelle.",
        body: "Schreibe oder sprich optional einen Gedanken ein. Er bleibt auf diesem Gerät, sofern du ihn nicht ausdrücklich exportierst. Arrive Within hat keine Werbung, Analyse, Nachverfolgung, Social-Funktion, Konto, Cloud-Synchronisierung oder Nutzerdaten-Server.",
        link: "Lies die Datenschutzerklärung",
      },
      open: {
        kicker: "Offen entwickelt",
        title: "Eine echte App, vorbereitet für öffentliche Zusammenarbeit.",
        body: "Quellcode, deterministischer Renderer, Inhaltsverträge, Tests, Website und Freigabenachweise leben gemeinsam in einem öffentlichen Repository. Für das echte Produkt ist keine private Zusatzschicht nötig.",
        link: "Entdecke das Open-Source-Projekt",
      },
    },
    support: {
      metaTitle: "Hilfe — Arrive Within",
      metaDescription: "Hilfe und Antworten zur Selbsthilfe für Arrive Within.",
      eyebrow: "Hilfe",
      title: "Unterstützung, ohne nach deinen privaten Daten zu fragen.",
      intro: "Diese Antworten beschreiben Version 1.0. Die App verlinkt aus den Einstellungen hierher und sendet keinen Supportbericht oder Produktdaten.",
      feedbackLabel: "Öffne Einstellungen und wähle Hilfe",
      feedbackNote: "Version 1.0 überträgt keine Rückmeldung aus der App. Der Hilfe-Link öffnet diese öffentliche Seite, ohne Praxis-, Journal-, Aufnahme-, Transkript-, Bildschirmfoto-, Protokoll- oder Gerätedaten anzuhängen.",
      faqs: [
        { q: "Braucht Arrive Within ein Konto?", a: "Nein. Praxis, Garten, Journal, Weg und Erinnerungen werden lokal gespeichert und funktionieren ohne Konto, Backend oder Cloud-Synchronisierung." },
        { q: "Enthält diese Version geführte Meditationen?", a: "Nein. Diese Version bietet den vollständigen Timer und die Stoppuhr. Eigene zweisprachige Offline-Meditationen sind für ein späteres Update geplant, sobald Rechte, Mastering und flüssige menschliche Hörprüfung bestanden sind." },
        { q: "Wie sichere oder übertrage ich meine Daten?", a: "Daten & Speicher erstellt ein lesbares Archiv, das du ausdrücklich über Apples Teilen-Funktion weitergeben kannst. Die App bewahrt keine Cloud-Kopie auf." },
        { q: "Kann ich alles löschen?", a: "Ja. Lokales Zurücksetzen und vollständiges Löschen sind ausdrücklich bestätigt. Sie entfernen Fortschritt, Journalinhalt und -audio, Einstellungen und app-eigene Exportarchive." },
        { q: "Sendet die App Hilfe- oder Nutzungsdaten?", a: "Nein. Version 1.0 verlinkt auf diese Hilfeseite, enthält aber weder Analyse, Werbung, Nachverfolgung, Backend, Cloud-Synchronisierung noch eine Rückmeldungsübertragung aus der App." },
        { q: "Ist die App eine medizinische Behandlung?", a: "Nein. Arrive Within ist ein weltliches Werkzeug für Meditation und Reflexion, keine medizinische Versorgung, Diagnose, Therapie oder Krisenhilfe." },
      ],
    },
    privacyPage: {
      metaTitle: "Datenschutz — Arrive Within",
      metaDescription: "Das Datenschutzversprechen von Arrive Within: lokale Gerätespeicherung, keine Datenerfassung und keine Nachverfolgung.",
      eyebrow: "Datenschutz",
      title: "Deine Praxis bleibt deine.",
      intro: "Gültig ab 12. August 2026. Diese Richtlinie beschreibt Arrive Within 1.0 und wird mit der App und dem öffentlichen Hilfeweg im Einklang gehalten.",
      sections: [
        { title: "Was die App speichert", paragraphs: ["Praxissitzungen, Gartenfortschritt, Einstellungen, Favoriten, Erinnerungspläne und optionale Journaltexte oder Sprachreflexionen werden auf deinem Gerät gespeichert.", "Sprachaufnahmen sind App-Daten. Die Transkription auf dem Gerät ist optional; Arrive Within sendet Aufnahmen nicht an einen eigenen KI-Dienst oder einen Browser-Sprachdienst."] },
        { title: "Wo die Daten bleiben", paragraphs: ["Version 1.0 speichert App-Daten auf diesem Gerät. Es gibt weder Konto, Backend noch Cloud-Synchronisierung.", "Daten verlassen die App nur, wenn du ausdrücklich ein Archiv erstellst und es über Apples Teilen-Funktion weitergibst. Geteilte Kopien werden anschließend vom gewählten Ziel verwaltet."] },
        { title: "Was wir nicht tun", paragraphs: ["Keine Drittanbieter-Analyse, Werbe-SDKs, Nachverfolgung, ATT-Abfrage, Social Graph, Newsletter, Datenhändler oder App-übergreifende Profile gehören zu 1.0.", "Der Renderer hat keine Netzwerkbefugnis. Dein Journal wird nicht für Empfehlungen, Bewertungen oder Werbung analysiert."] },
        { title: "Hilfe", paragraphs: ["Einstellungen verlinkt auf die öffentlichen Hilfe- und Datenschutzseiten. Version 1.0 erstellt oder überträgt keinen Rückmeldungsbericht in der App.", "Praxis- oder Journalinhalte, Aufnahmen, Transkripte, Bildschirmfotos, Zwischenablage, Darstellungszustand, Protokolle, Zugangsdaten, Analysen und Kennungen werden diesen Links nicht angehängt."] },
        { title: "Berechtigungen", paragraphs: ["Mikrofonzugriff wird nur angefragt, wenn du eine Sprachreflexion aufnimmst. Spracherkennung nur bei gewählter Transkription auf dem Gerät. Mitteilungen nur beim Erstellen von Erinnerungen.", "Eine Ablehnung lässt den Rest der App nutzbar und bewahrt bereits eingegebenen Text."] },
        { title: "Export, Zurücksetzen und Löschen", paragraphs: ["Du kannst ein lesbares Archiv erstellen und lokale Daten ausdrücklich zurücksetzen oder löschen. App-eigene Exportarchive sind geschützt, von Backups ausgeschlossen, auf eines begrenzt, werden nach dem Schließen der Teilen-Funktion entfernt und beim Zurücksetzen oder vollständigen Löschen bereinigt.", "Prüfe ein Archiv vor dem Teilen auf private Inhalte. Die App kann Kopien, die du ausdrücklich anderswo teilst, nicht entfernen."] },
        { title: "Fragen und Aktualisierungen", paragraphs: ["Die kanonische Hilfeseite ist /de/support.", "Diese Richtlinie wird mit dem exakten App-Binary, PrivacyInfo.xcprivacy, den App-Privacy-Angaben, Berechtigungstexten und dem öffentlichen Hilfeweg im Einklang gehalten."] },
      ],
    },
    openSourcePage: {
      metaTitle: "Open Source — Arrive Within",
      metaDescription: "Entdecke den kanonischen öffentlichen Quellcode der Arrive Within App für iPhone und iPad und wirke daran mit.",
      eyebrow: "Open-Source-Versprechen",
      title: "Das öffentliche Repository ist das echte Produkt.",
      intro: "Arrive Within wird in einem kanonischen öffentlichen Repository entwickelt, dessen gesamte nachverfolgte Historie ab dem ersten Commit sicher einsehbar ist.",
      principles: [
        { title: "Kein Demo-Fork", text: "Native App, Renderer, Inhaltsverträge, Website, Tests und Freigabenachweise gehören zusammen. Hinter einer öffentlichen Hülle liegt keine private Produktimplementierung." },
        { title: "Reproduzierbare Nachweise", text: "Deterministische Fixtures und öffentlich sichere Ledgers trennen lokale Tests, Simulator, echte Geräte, CloudKit, TestFlight, App Store und Deployment-Readback." },
        { title: "Rechte vor Assets", text: "Kopierte Referenzkunst, unklare Stimmen, proprietäres Verhalten und ungeprüfte Medien gelangen nicht in die öffentliche Historie." },
        { title: "Datenschutz als Architektur", text: "Die App ist lokal ausgerichtet, hat kein Tracking und keinen eigenen Nutzerdaten-Server; der Renderer besitzt keine Produktwahrheit." },
      ],
      repoLabel: "Quellcode auf GitHub ansehen",
      repoNote: "Durchsuche App, Renderer, Tests, Leitfäden und öffentliche Nachweise oder schlage eine gezielte Verbesserung vor.",
    },
  },
};
