import type { GardenVisualDirection } from "../visual-design";

export const paperSanctuary: GardenVisualDirection = {
  id: "paper-sanctuary",
  name: "Paper Sanctuary",
  meaning: "A quiet illustrated refuge assembled from tactile layers of remembered practice.",
  foliageForm: "paper-relief",
  palette: {
    skyTint: "#d9d5bd",
    groundTint: "#7f8161",
    foliageTint: "#718060",
    accentTint: "#bd855a",
    detailTint: "#9b8b70",
    influence: 0.58,
    skyInfluence: 0.68,
    groundInfluence: 0.52,
    foliageInfluence: 0.46,
    accentInfluence: 0.58,
    trunk: "#76563f",
  },
  lighting: {
    hemisphereSky: "#f2ead7",
    hemisphereGround: "#625d4d",
    hemisphereIntensity: 2.04,
    sunTint: "#f4c98d",
    sunIntensityScale: 0.88,
    exposure: 1.03,
    fogNear: 14,
    fogFar: 34,
    fillColor: "#d8aa77",
    fillIntensity: 14,
    fillPosition: [3.8, 4.2, 5.5],
  },
  composition: {
    cameraDistanceScale: 1.1,
    cameraHeightOffset: 0.15,
    targetHeightOffset: 0.12,
    groundLayers: 4,
    canopyScale: [1.1, 1.02, 0.58],
    particleSize: 0.05,
    particleOpacity: 0.42,
    waterOpacity: 0.72,
  },
  motion: { canopyAmplitude: 0.44, particleSpeed: 0.6 },
  detailOverrides: {
    stones: "#a39c83",
    stream: "#88a8a1",
    pond: "#7d9e98",
    blossoms: "#cf8f76",
    clouds: "#ded8c8",
  },
};
