import { createGardenStyleProfile, type GardenVisualDirection } from "../visual-design";

export const twilightRefuge: GardenVisualDirection = {
  id: "twilight-refuge",
  name: "Twilight Refuge",
  meaning: "An indigo evening sanctuary where each practice leaves a restrained amber light.",
  foliageForm: "twilight-silhouette",
  palette: {
    skyTint: "#252f55",
    groundTint: "#253d3d",
    foliageTint: "#4f7165",
    accentTint: "#e6ae63",
    detailTint: "#496c68",
    influence: 0.72,
    skyInfluence: 0.84,
    groundInfluence: 0.76,
    foliageInfluence: 0.5,
    accentInfluence: 0.84,
    trunk: "#443b3b",
  },
  lighting: {
    hemisphereSky: "#69749a",
    hemisphereGround: "#1c3534",
    hemisphereIntensity: 1.92,
    sunTint: "#e7aa67",
    sunIntensityScale: 0.72,
    exposure: 1.08,
    fogNear: 13,
    fogFar: 32,
    fillColor: "#efaa58",
    fillIntensity: 26,
    fillPosition: [3.5, 2.8, 5.2],
  },
  composition: {
    cameraDistanceScale: 1.16,
    cameraHeightOffset: 0.22,
    targetHeightOffset: 0.2,
    groundLayers: 2,
    canopyScale: [0.96, 1.12, 0.74],
    particleSize: 0.055,
    particleOpacity: 0.7,
    waterOpacity: 0.78,
  },
  motion: { canopyAmplitude: 0.54, particleSpeed: 0.72 },
  styleProfile: createGardenStyleProfile({
    surfacePattern: "natural-grain",
    edgeMode: "none",
    shadingBands: 2,
    geometryTreatment: "organic",
    detailDensity: 1,
    motionCadence: { framesPerSecond: 60, propJitter: 0, inkWobble: 0, squashStretch: 0 },
    skyAccents: { horizonTint: "#252f55", celestialTint: "#e6ae63", strength: 0 },
    waterAccents: { tint: "#496c68", opacity: 1, rippleScale: 1 },
    seeds: { texture: 0x51c3d, motion: 0x72f19, geometry: 0xa41e7 },
    materialRoles: {
      canopy: { roughness: 0.9, flatShading: true },
      trunk: { roughness: 0.96, flatShading: true },
      ground: { roughness: 1, flatShading: true },
      grass: { roughness: 0.94, flatShading: true },
      water: { roughness: 0.3, flatShading: false },
      pavilion: { roughness: 0.92, flatShading: true },
      path: { roughness: 1, flatShading: true },
      rock: { roughness: 0.94, flatShading: true },
      wildlife: { roughness: 0.96, flatShading: true },
      celestial: { roughness: 1, flatShading: true, textureOpacity: 0 },
    },
  }),
  detailOverrides: {
    stream: "#436f75",
    pond: "#385e69",
    "warm-light": "#e6aa5c",
    fireflies: "#f2c66d",
    blossoms: "#b77f77",
    "twilight-stars": "#eee1b7",
    moon: "#ecd9aa",
  },
};
