import type { GardenVisualDirection } from "../visual-design";

export const verdantAtelier: GardenVisualDirection = {
  id: "verdant-atelier",
  name: "Verdant Atelier",
  meaning: "A living botanical refuge shaped by patient practice and warm natural light.",
  foliageForm: "painted-botanical",
  palette: {
    skyTint: "#b9d5c1",
    groundTint: "#496846",
    foliageTint: "#527d50",
    accentTint: "#ddb365",
    detailTint: "#72916b",
    influence: 0.22,
    skyInfluence: 0.58,
    groundInfluence: 0.32,
    foliageInfluence: 0.12,
    accentInfluence: 0.34,
    trunk: "#684a32",
  },
  lighting: {
    hemisphereSky: "#eaf5df",
    hemisphereGround: "#304936",
    hemisphereIntensity: 2.18,
    sunTint: "#ffe0a0",
    sunIntensityScale: 1.04,
    exposure: 1.08,
    fogNear: 14,
    fogFar: 34,
    fillColor: "#d6b86f",
    fillIntensity: 18,
    fillPosition: [4.2, 3.6, 4.8],
  },
  composition: {
    cameraDistanceScale: 1.12,
    cameraHeightOffset: 0,
    targetHeightOffset: 0,
    groundLayers: 2,
    canopyScale: [1.13, 1, 0.9],
    particleSize: 0.045,
    particleOpacity: 0.58,
    waterOpacity: 0.84,
  },
  motion: { canopyAmplitude: 1, particleSpeed: 1 },
  detailOverrides: {
    stream: "#6faaa0",
    pond: "#679a91",
    blossoms: "#e3a37e",
    "warm-light": "#efb966",
  },
};
