#!/bin/zsh
set -euo pipefail

script_directory="${0:A:h}"
project_root="${script_directory:h}"
output_directory="${project_root}/Apps/ArriveWithin/Resources/Audio"

if [[ ! -f "${project_root}/SPEC.md" || "$output_directory" != "${project_root}"/* ]]; then
  print -u2 "Refusing to generate outside the Arrive Within checkout."
  exit 64
fi
if ! command -v ffmpeg >/dev/null || ! command -v jq >/dev/null; then
  print -u2 "ffmpeg and jq are required."
  exit 69
fi

/bin/mkdir -p "$output_directory"

regenerate_ambience=0
if [[ "${1:-}" == "--regenerate-ambience" ]]; then
  regenerate_ambience=1
elif [[ -n "${1:-}" ]]; then
  print -u2 "Usage: $0 [--regenerate-ambience]"
  exit 64
fi

ffmpeg -hide_banner -loglevel error -y \
  -f lavfi -i "sine=frequency=523.251:sample_rate=48000:duration=3.8" \
  -f lavfi -i "sine=frequency=784.877:sample_rate=48000:duration=3.8" \
  -f lavfi -i "sine=frequency=1046.502:sample_rate=48000:duration=3.8" \
  -filter_complex \
  "[0:a]volume=0.16,afade=t=out:st=0.08:d=3.72:curve=exp[a0];[1:a]volume=0.08,afade=t=out:st=0.04:d=3.76:curve=exp[a1];[2:a]volume=0.04,afade=t=out:st=0.02:d=3.78:curve=exp[a2];[a0][a1][a2]amix=inputs=3:normalize=0,aecho=0.65:0.32:95|190:0.20|0.10,volume=33dB,alimiter=limit=0.70" \
  -ar 48000 -ac 1 -c:a pcm_s16le \
  "${output_directory}/opening-bell-v1.wav"

ffmpeg -hide_banner -loglevel error -y \
  -f lavfi -i "sine=frequency=392.000:sample_rate=48000:duration=5.2" \
  -f lavfi -i "sine=frequency=587.330:sample_rate=48000:duration=5.2" \
  -f lavfi -i "sine=frequency=783.991:sample_rate=48000:duration=5.2" \
  -filter_complex \
  "[0:a]volume=0.15,afade=t=out:st=0.10:d=5.10:curve=exp[a0];[1:a]volume=0.075,afade=t=out:st=0.05:d=5.15:curve=exp[a1];[2:a]volume=0.035,afade=t=out:st=0.03:d=5.17:curve=exp[a2];[a0][a1][a2]amix=inputs=3:normalize=0,aecho=0.70:0.28:120|260:0.18|0.08,volume=29dB,alimiter=limit=0.70" \
  -ar 48000 -ac 1 -c:a pcm_s16le \
  "${output_directory}/closing-bell-v1.wav"

if (( regenerate_ambience )); then
  ffmpeg -hide_banner -loglevel error -y \
    -f lavfi \
    -i "aevalsrc=0.004*sin(2*PI*55*t)*(0.72+0.28*cos(2*PI*0.05*t))+0.004*sin(2*PI*110*t)*(0.78+0.22*cos(2*PI*0.10*t))+0.006*sin(2*PI*220*t)*(0.80+0.20*cos(2*PI*0.05*t))+0.003*sin(2*PI*330*t)*(0.82+0.18*cos(2*PI*0.10*t))+0.0015*sin(2*PI*440*t):sample_rate=48000:duration=20" \
    -af "highpass=f=35,lowpass=f=1200,volume=14dB,alimiter=limit=0.35" \
    -ar 48000 -ac 1 -c:a aac -b:a 64k -movflags +faststart \
    "${output_directory}/still-air-v1.m4a"
elif [[ ! -f "${output_directory}/still-air-v1.m4a" ]]; then
  print -u2 "The selected ambience master is missing; rerun with --regenerate-ambience only for an explicitly approved replacement."
  exit 66
fi

opening_sha="$(/usr/bin/shasum -a 256 "${output_directory}/opening-bell-v1.wav" | /usr/bin/awk '{print $1}')"
closing_sha="$(/usr/bin/shasum -a 256 "${output_directory}/closing-bell-v1.wav" | /usr/bin/awk '{print $1}')"
ambience_sha="$(/usr/bin/shasum -a 256 "${output_directory}/still-air-v1.m4a" | /usr/bin/awk '{print $1}')"

if [[ -z "$opening_sha" || -z "$closing_sha" || -z "$ambience_sha" ]]; then
  print -u2 "A generated asset hash is missing."
  exit 70
fi

jq -n --sort-keys \
  --arg ffmpeg "$(ffmpeg -version | /usr/bin/head -1)" \
  --arg opening "$opening_sha" \
  --arg closing "$closing_sha" \
  --arg ambience "$ambience_sha" \
  '{
    schema_version: 1,
    generator: $ffmpeg,
    rights: "Original deterministic synthesis generated by this repository; no samples, recordings, reference voices, or third-party media.",
    mastering: "Opening and closing bell synthesis receives 33 dB and 29 dB of deterministic output gain respectively before a 0.70 limiter. Still Air retains low warmth, adds device-audible harmonics, and receives 14 dB of output gain before a 0.35 limiter. Bundled validation rejects inaudible or clipping procedural layers.",
    generation_scope: "The default command remasters both bells and preserves the exact selected ambience master. Pass --regenerate-ambience only for an explicitly approved, hash-bound ambience replacement.",
    human_qa: "pending",
    assets: [
      {id: "opening-bell-v1", path: "Audio/opening-bell-v1.wav", sha256: $opening, role: "opening-bell", format: "PCM s16le, 48 kHz, mono"},
      {id: "closing-bell-v1", path: "Audio/closing-bell-v1.wav", sha256: $closing, role: "closing-and-interval-bell", format: "PCM s16le, 48 kHz, mono"},
      {id: "still-air-v1", path: "Audio/still-air-v1.m4a", sha256: $ambience, role: "optional-looping-ambience", format: "AAC 64 kbps, 48 kHz, mono"}
    ]
  }' > "${output_directory}/audio-assets.json"

print "Generated original audio assets in ${output_directory}."
